#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import os, secrets
from ..banner import Colors, print_info, print_success

class MeshSkill:
    id = "mesh"
    name_es = "Sentinel Mesh (Monitoreo Multi-Servidor para Laboratorios)"
    name_en = "Sentinel Mesh (Multi-Server Lab Fleet Monitoring)"
    desc_es = "Conecta múltiples servidores secundarios a un núcleo central para telemetría en vivo."
    desc_en = "Connect multiple secondary servers to a central core for real-time telemetry."

    def __init__(self):
        self.role = "core" # core or agent
        self.core_token = ""

    def configure_interactive(self, lang="es"):
        print(f"\n{Colors.BOLD}{Colors.CYAN}--- CONFIGURANDO SKILL: Sentinel Mesh ---{Colors.RESET}")
        
        prompt_role = (
            "¿Cuál es el rol de este servidor en el laboratorio?\n"
            "  [1] Servidor Principal (CORE) - Recibe métricas y comanda a los demás\n"
            "  [2] Nodo Satélite (AGENT)     - Reporta métricas a un Core existente\n"
            "Selección [1]: "
        ) if lang == "es" else (
            "What is the role of this server in the laboratory fleet?\n"
            "  [1] Central Server (CORE) - Gathers metrics and controls other nodes\n"
            "  [2] Satellite Node (AGENT) - Reports telemetry to an existing Core\n"
            "Selection [1]: "
        )
        
        choice = input(prompt_role).strip()
        if choice == "2":
            self.role = "agent"
            prompt_token = "Introduce el TOKEN de vinculación generado por tu Core: " if lang == "es" else "Enter the pairing TOKEN generated by your Core: "
            self.core_token = input(prompt_token).strip()
        else:
            self.role = "core"
            self.core_token = secrets.token_hex(16)
            print_info(f"Token de vinculación generado para este Core: {self.core_token}")

        os.makedirs("config", exist_ok=True)
        with open("config/mesh.env", "w", encoding="utf-8") as f:
            f.write(f"SENTINEL_MESH_ROLE={self.role}\n")
            f.write(f"SENTINEL_MESH_TOKEN={self.core_token}\n")

        print_success("Configuración de Sentinel Mesh guardada en config/mesh.env")
